import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import NextAuthProvider from "@/provider/NextAuthProvider";
// import NextAuthProvider from "@/provider/NextAuthProvider";

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
});
export const metadata = {
  title: "Next Auth Form",
  description: "Generated by next auth and next js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <NextAuthProvider>
          <Navbar></Navbar>

          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
