import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
});
export const metadata = {
  title: "Next Auth Form",
  description: "Generated by next auth and next js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <Navbar></Navbar>

        {children}
      </body>
    </html>
  );
}
